language: java
sudo: false # faster builds

jdk:
    - openjdk8

addons:
    sonarcloud:
        organization: "canmogol-github"
        token:
            secure: "No1fOEO7qopFonp14num6EDv+i6JoZ4GZN2d/w9YK4BTUMcCjuBGvUx7m2sMeJ6JPag+IOITm+EhJGBC1H82ZaZw9kzj8DvkFGQU0xKXG92x4i/5qEfXFmsOdXwCnafTHp/Z3/rIf2CAzucb26heevCRKdDCzXZm2PAeX0hyTDD29418nRbLB9bZMsicP+hHib8bdb1HINVqa9K3U+mce2fcWCqkgWlTQFV+pH38lSX22bOFQGJ8+o0AOdsoyDNbwLx5ahlB0e5Ji6oBw3A0RefgwLepc/hmIXjnZM0Rr1HAPBGSCCn906kmd0lEQA07HdpCutCx2Pb2fcnfLayKwpnHYqgZONljeOdd7oSos/Cv6edMjWguUQGZttb+WxqLezO293VFBfOXfOSPOcshIeqObR2Q+v1+gyt0cEbquMhJySugQFVLs05TA1Gi4Tyuyg47Gvif/8ubCqhBB4pTxWJ0Gy8TB1UgyPPl0cRgd+sTSuTlzNLAxpQBk7J0yR8VppnvsjYFVVBSqHkVjR3vHSoxKx1MAU6X+OThg9LAmDP622YrBjFvSCAJkIB5eVwUMc3QPp9zW8l3QKgEt43jfNe1pHw3zvDRDcs3Z3MRHgfHiIPSBka7lXZsM7U4qWHcy8hLi5qZJHi5efsaNvTLYdyGd8Ugu//oGu6Le7Glnbw="
            
cache:
    directories:
        - $HOME/.m2

install: true

script:
    - mvn clean install
    - mvn sonar:sonar
